### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by ByteNinja64** [crmulent/FaSeek#1]
Hello, 
Thank you for your work !
It seems that pimeyes api is discontinued ? Do you know where i can find my api key ?
On the website i got an ID code with my advanced plan, but it does not work

Thank you !

**Comment by crmulent** [comment]
To make the code work, you'll need [ScrapingBee's API](https://www.scrapingbee.com/). Additionally, while making the program, I only had access to the basic plan, so I may not be familiar with other features, such as the ID code you mentioned.
